### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'datetime'

### ISSUE THREAD

**Issue by vikasrajpoot0100** [AI4Finance-Foundation/FinNLP#25]
when i run the code : 
```
# Finnhub (Yahoo Finance, Reuters, SeekingAlpha, CNBC...)
from finnlp.data_sources.news.finnhub_date_range import Finnhub_Date_Range

start_date = "2023-01-01"
end_date = "2023-01-03"
config = {
    "use_proxy": "us_free",    # use proxies to prvent ip blocking
    "max_retry": 5,
    "proxy_pages": 5,
    "token": "YOUR_FINNHUB_TOKEN"  # Available at https://finnhub.io/dashboard
}

news_downloader = Finnhub_Date_Range(config)                      # init
news_downloader.download_date_range_stock(start_date,end_date)    # Download headers
news_downloader.gather_content()                                  # Download contents
df = news_downloader.dataframe
selected_columns = ["headline", "content"]
df[selected_columns].head(10)
```
the fellowing error is through. 
Checking ips: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 75/75 [01:04<00:00,  1.16it/s]
Get proxy ips: 75.
Usable proxy ips: 75.
stoped--
Downloading Titles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:04<00:00,  1.45s/it]
stop 
Traceback (most recent call last):
  File "/home/bbbs/Videos/FINTECH/main.py", line 15, in <module>
    news_downloader.download_date_range_stock(start_date,end_date)    # Download headers
  File "/home/bbbs/Videos/FINTECH/FinNLP/finnlp/data_sources/news/finnhub_date_range.py", line 50, in download_date_range_stock
    self.dataframe.datetime = pd.to_datetime(self.dataframe.datetime,unit = "s")
  File "/home/bbbs/anaconda3/envs/fin_nlp/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'datetime'

**Comment by vikasrajpoot0100** [comment]
Error Solved increase the range of the days start_date = "2023-01-01"
end_date = "2023-01-03"

if there is no data comes the this error is through.
